version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: eetstudio_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      # Dit zorgt ervoor dat onze tabellen direct worden aangemaakt bij de eerste start:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mariadb_data: